---
Name: silverstripe-intercom-userforms
---
Form:
  extensions:
    - 'SilverStripe\Intercom\FormExtension'
EditableFormField:
  extensions:
    - IntercomEditableFormField
UserDefinedForm:
  extensions:
    - IntercomUserDefinedFormExtension
UserForm:
  extensions:
    - IntercomUserFormExtension